version: "3.9"
services:
  pgweb:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "0.14.2"
        PGWEB_VERSION: "0.14.2"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "pgweb:build"
        - "gautada/pgweb:build"
    image: "pgweb:build"
    environment:
    - PGWEB_DATABASE_URL=postgres://pgweb@psql.gautier.org:5432/postgres?connect_timeout=30&sslmode=disable
    ports:
      - "8080:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"

volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"