version: "3.9"
services:
  pgweb:
    build:
      args:
        ALPINE_VERSION: "latest"
        PGWEB_VERSION: "0.14.2"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "pgweb:build"
        - "gautada/pgweb:build"
    image: "pgweb:build"
    ports:
      - "8080:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"

volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"