version: "3.9"
services:
  pgweb:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "0.14.2"
        PGWEB_VERSION: "0.14.2"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "pgweb:build"
        - "gautada/pgweb:build"
        - "gautada/pgweb:latest"
    image: "pgweb:build"
    environment:
    # postgres://pgweb@[HOST.DOMAIN.TLD]:5432/postgres?connect_timeout=30&sslmode=disable
    - PGWEB_DATABASE_URL=${COMPOSE_PGWEB_DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"

volumes:
      Container:
        external: true
        name: "Container"
      
      Backup:
        external: true
        name: "Backup"
      
      Configmaps:
        external: true
        name: "Configmaps"
        
      Secrets:
        external: true
        name: "Secrets"
