#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="pgweb"

container_entrypoint() {
 /usr/bin/pgweb --bind 0.0.0.0 --listen 8080 --debug --lock-session --url postgres://pgweb:postgresql.data.svc.cluster.local:5432 --user pgweb
}

container_version() {
 echo "0.0.0"
}



start_app() {
 /usr/bin/pgweb --bind 0.0.0.0 --listen 8080 --host localhost --user $1
}

