#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="pgweb"

container_entrypoint() {
 QUERIES_FOLDER="/mnt/volumes/container/pgweb/queries"
 if [ ! -d  $QUERIES_FOLDER ] ; then
  /bin/mkdir -p $QUERIES_FOLDER
 fi
 /usr/bin/pgweb --log-level=debug --bind=0.0.0.0 --listen=8080 --db=postgres
}

container_version() {
 pgweb --version | awk -F ' ' '{print $2}' | cut -c 2-
}

